import Link from "next/link";

const linkStyle = { color: '#303030', textDecoration: 'underline' };

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <head>
          <link
              href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
              rel="stylesheet"
          />
        </head>
        <body style={{fontFamily: "'Roboto', sans-serif"}}>
            <div style={{margin: '2rem'}}>
                <main>
                    <nav style={{display: 'flex', gap: '0.5rem'}}>
                        <Link href="/" style={linkStyle}>
                            Home
                        </Link>
                        <Link href="/notes" style={linkStyle}>
                            Notes
                        </Link>
                    </nav>
                    {children}
                </main>
            </div>
        </body>
      </html>
)
}
